preprocess:
  input: data/raw/data.csv
  output: data/processed/data_cleaned.csv

train:
  input: data/processed/data_cleaned.csv
  model: "models/rf_model.pkl"
  output: models/trained_model.pkl
  parameters:
    n_estimators: 100
    max_depth: 5
    random_state: 42
